FETCH 1
EXECUTE_LOAD_STORE 1
MOVE_STATE_REG_DOWN 1

FETCH 2
EXECUTE_LOAD_STORE 2
MOVE_STATE_REG_DOWN 2

FETCH 3
EXECUTE_LOAD_STORE 3
MOVE_STATE_REG_DOWN 3

; ...

FETCH 2
EXECUTE_LOAD_STORE 2
MOVE_STATE_REG_DOWN 2

FETCH 1
EXECUTE_LOAD_STORE 1
MOVE_STATE_REG_DOWN 1

FETCH 0
EXECUTE_LOAD_STORE 0

ASSIGN_LOADED 0
INCREMENT_P 0
DECODE_EXECUTE_TRANSFER 0
DECODE_EXECUTE_ARITHMETIC_LOGIC 0
DECODE_EXECUTE_SET 0
DECODE_EXECUTE_BRANCH 0
DECODE_LOAD_STORE 0