package tetrominocomputer.tse.ui;

import tetrominocomputer.util.Ui;

public class FindReplacePanel extends javax.swing.JPanel {

    private CircuitsFrame circuitsFrame;
    
    /**
     * Creates new form FindPanel
     */
    public FindReplacePanel() {
        initComponents();
        Ui.setTextFieldColumns(findWhatTextField, 40);
        Ui.setTextFieldColumns(replaceWithTextField, 40);
    }
    
    public void setCircuitsFrame(final CircuitsFrame circuitsFrame) {
        this.circuitsFrame = circuitsFrame;
    }    
    
    public void setReplaceEnabled(final boolean replaceEnabled) {
        replaceButton.setVisible(replaceEnabled);
        replaceAllButton.setVisible(replaceEnabled);
        replaceWithLabel.setVisible(replaceEnabled);
        replaceWithTextField.setVisible(replaceEnabled);        
    }
    
    public void init() {
        findWhatTextField.requestFocusInWindow();
        findWhatTextField.selectAll();
        Ui.resetTextFieldColumns(findWhatTextField);
        Ui.resetTextFieldColumns(replaceWithTextField);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findWhatLabel = new javax.swing.JLabel();
        replaceWithLabel = new javax.swing.JLabel();
        findNextButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        replaceAllButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        findWhatTextField = new javax.swing.JTextField();
        replaceWithTextField = new javax.swing.JTextField();
        backwardCheckBox = new javax.swing.JCheckBox();
        matchCaseCheckBox = new javax.swing.JCheckBox();
        regExCheckBox = new javax.swing.JCheckBox();
        wrapCheckBox = new javax.swing.JCheckBox();

        findWhatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        findWhatLabel.setText(" Find what :");
        findWhatLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        replaceWithLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        replaceWithLabel.setText("Replace with :");
        replaceWithLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        findNextButton.setMnemonic('F');
        findNextButton.setText("Find Next");
        findNextButton.setMargin(new java.awt.Insets(0, 14, 2, 14));
        findNextButton.setNextFocusableComponent(replaceButton);
        findNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNextButtonActionPerformed(evt);
            }
        });

        replaceButton.setMnemonic('R');
        replaceButton.setText("Replace");
        replaceButton.setNextFocusableComponent(replaceAllButton);
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        replaceAllButton.setMnemonic('A');
        replaceAllButton.setText("Replace All");
        replaceAllButton.setNextFocusableComponent(closeButton);
        replaceAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceAllButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.setNextFocusableComponent(findWhatTextField);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        findWhatTextField.setColumns(40);
        findWhatTextField.setFocusCycleRoot(true);
        findWhatTextField.setNextFocusableComponent(replaceWithTextField);
        findWhatTextField.setPreferredSize(null);
        findWhatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findWhatTextFieldActionPerformed(evt);
            }
        });

        replaceWithTextField.setColumns(40);
        replaceWithTextField.setNextFocusableComponent(backwardCheckBox);

        backwardCheckBox.setMnemonic('b');
        backwardCheckBox.setText("Backward direction");
        backwardCheckBox.setNextFocusableComponent(matchCaseCheckBox);

        matchCaseCheckBox.setMnemonic('c');
        matchCaseCheckBox.setText("Match case");
        matchCaseCheckBox.setNextFocusableComponent(regExCheckBox);

        regExCheckBox.setMnemonic('g');
        regExCheckBox.setText("Regular expression");
        regExCheckBox.setNextFocusableComponent(wrapCheckBox);

        wrapCheckBox.setMnemonic('p');
        wrapCheckBox.setSelected(true);
        wrapCheckBox.setText("Wrap around");
        wrapCheckBox.setNextFocusableComponent(findNextButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(replaceWithLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(findWhatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(findWhatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(replaceWithTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backwardCheckBox)
                                    .addComponent(matchCaseCheckBox)
                                    .addComponent(regExCheckBox)
                                    .addComponent(wrapCheckBox))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(findNextButton)
                                .addComponent(replaceButton, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(replaceAllButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(8, 8, 8))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {findWhatLabel, replaceWithLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeButton, findNextButton, replaceAllButton, replaceButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(findNextButton)
                .addGap(0, 0, 0)
                .addComponent(replaceButton)
                .addGap(0, 0, 0)
                .addComponent(replaceAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findWhatLabel)
                    .addComponent(findWhatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceWithLabel)
                    .addComponent(replaceWithTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(backwardCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matchCaseCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regExCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrapCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNextButtonActionPerformed
        circuitsFrame.findNext(findWhatTextField.getText(), backwardCheckBox.isSelected(), 
                matchCaseCheckBox.isSelected(), regExCheckBox.isSelected(), wrapCheckBox.isSelected());
    }//GEN-LAST:event_findNextButtonActionPerformed

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        circuitsFrame.replace(findWhatTextField.getText(), replaceWithTextField.getText(), 
                backwardCheckBox.isSelected(), matchCaseCheckBox.isSelected(), regExCheckBox.isSelected(), 
                wrapCheckBox.isSelected());
    }//GEN-LAST:event_replaceButtonActionPerformed

    private void replaceAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceAllButtonActionPerformed
        circuitsFrame.replaceAll(findWhatTextField.getText(), replaceWithTextField.getText(), 
                backwardCheckBox.isSelected(), matchCaseCheckBox.isSelected(), regExCheckBox.isSelected(), 
                wrapCheckBox.isSelected());
    }//GEN-LAST:event_replaceAllButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        circuitsFrame.closeFindReplaceDialog();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void findWhatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findWhatTextFieldActionPerformed
        findNextButtonActionPerformed(evt);
    }//GEN-LAST:event_findWhatTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backwardCheckBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton findNextButton;
    private javax.swing.JLabel findWhatLabel;
    private javax.swing.JTextField findWhatTextField;
    private javax.swing.JCheckBox matchCaseCheckBox;
    private javax.swing.JCheckBox regExCheckBox;
    private javax.swing.JButton replaceAllButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JLabel replaceWithLabel;
    private javax.swing.JTextField replaceWithTextField;
    private javax.swing.JCheckBox wrapCheckBox;
    // End of variables declaration//GEN-END:variables
}
